name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        https://github.com/qgsoriano1/cpe_soriano_ansible.git 
        https://github.com/qgsoriano1/testAnsible.git 
        https://github.com/qgsoriano1/CPE232_Soriano.git 
        https://github.com/qgsoriano1/Soriano_PrelimExam.git 
        https://github.com/qgsoriano1/Soriano_Act8F.git 
        https://github.com/qgsoriano1/Soriano_Act9.git 
        https://github.com/qgsoriano1/Soriano_Act10.git 
        https://github.com/qgsoriano1/CPE_MIDEXAM_SORIANO.git 
        https://github.com/qgsoriano1/HOA11_Soriano.git 
        https://github.com/qgsoriano1/HOA12.1_Soriano.git 
        https://github.com/qgsoriano1/HOA13.1_Soriano.git 
        https://github.com/qgsoriano1/HOA14.1_Soriano.git 
        https://github.com/qgsoriano1/HOA15.1_Soriano.git 
        https://github.com/qgsoriano1/Final_Exam_Soriano.git
